Repository jenkinsci/docker-workflow-plugin, pull requests merged in 2019-10, with the labels that each got.

#191 [JENKINS-59172] - Use GitHub as a source of the plugin's documentation on plugins.jenkins.io
  pom.xml
Labels: documentation, hacktoberfest

#187 Add Container ID detection for GitHub Actions
  src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java
Labels: enhancement

#190 Enable Release Drafter in the Repository
  .github/release-drafter.yml
Labels: chore, hacktoberfest

#192 Move changelog to GitHub, add badges for the plugin site and release stats
  README.md
Labels: documentation

#184 Features/windows agents with pathing issues fixed
  src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
  src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
  src/main/java/org/jenkinsci/plugins/docker/workflow/client/WindowsDockerClient.java
  src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
  src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java
  src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
  src/test/java/org/jenkinsci/plugins/docker/workflow/client/WindowsDockerClientTest.java
Labels: enhancement
