Repository jenkinsci/docker-workflow-plugin, pull requests merged in 2025-02, with the labels that each got.

#329 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfig.java
  src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
  src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java
  src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerDirectiveGeneratorTest.java
Labels: internal

#337 Adapt to Declarative change
  pom.xml
  src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/AbstractDockerPipelineScript.groovy
  src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipelineFromDockerfileScript.groovy
  src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipelineScript.groovy
Labels: bug

#338 Skip `agentDockerWithCreds` unless both `docker.username` and `docker.password` are set
  src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerAgentTest.java
Labels: developer

#339 Deleting `agentDockerWithCreds` test
  src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerAgentTest.java
  src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithCreds.groovy
Labels: developer
